# fly.toml app configuration file generated for kkh-chatbot-api on 2025-07-07T13:10:19+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kkh-chatbot-api'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
